from pathlib import Path

MODEL_NAME = "gpt-4o-mini"
N_ROUNDS = 8
TEAM_GOAL_SCORE = 20
MAX_HINT_NUMBER = 4
AI_REROLLS_PER_GAME = 2
HUMAN_REROLLS_PER_GAME = 2
TOTAL_HINT_CHANCES = AI_REROLLS_PER_GAME + HUMAN_REROLLS_PER_GAME
DATA_FILE = Path("game_data.csv")

