from pathlib import Path

MODEL_NAME = "gpt-4o-mini"
N_ROUNDS = 4
MAX_TEAM_SCORE = 20
TEAM_GOAL_SCORE = 12
MAX_HINT_NUMBER = 5
BOARD_SIZE = 15
TARGET_COUNT = 5
BOMB_COUNT = 1
MAX_INTERACTIONS_PER_ROUND = 4
MAX_SKIPS_PER_ROUND = 2
MEDAL_POINTS = {
    "gold": 5,
    "silver": 4,
    "bronze": 3,
    "none": 0,
}
AI_REROLLS_PER_GAME = 2
HUMAN_REROLLS_PER_GAME = 2
TOTAL_HINT_CHANCES = AI_REROLLS_PER_GAME + HUMAN_REROLLS_PER_GAME
DATA_FILE = Path("game_data.csv")
