from pathlib import Path

HINT_MODEL_NAME = "gpt-4o"
GUESS_MODEL_NAME = "gpt-4o"
REFLECTION_MODEL_NAME = "gpt-4o"

MODEL_NAME = HINT_MODEL_NAME

N_ROUNDS = 4
MAX_TEAM_SCORE = 20
TEAM_GOAL_SCORE = 12
MAX_HINT_NUMBER = 5
BOARD_SIZE = 16
TARGET_COUNT = 5
BOMB_COUNT = 2
MAX_INTERACTIONS_PER_ROUND = 3
MAX_SKIPS_PER_ROUND = 2
CLUE_TIMER_SECONDS = 120
MEDAL_POINTS = {
    "gold": 5,
    "silver": 4,
    "bronze": 3,
    "none": 0,
}
AI_REROLLS_PER_GAME = 2
HUMAN_REROLLS_PER_GAME = 2
TOTAL_HINT_CHANCES = AI_REROLLS_PER_GAME + HUMAN_REROLLS_PER_GAME
DATA_DIR = Path("data")
ROUND_DATA_FILE = DATA_DIR / "game_rounds.csv"
INTERACTION_DATA_FILE = DATA_DIR / "game_interactions.csv"
SESSIONS_DATA_FILE = DATA_DIR / "sessions.csv"
ROUNDS_DATA_FILE = DATA_DIR / "rounds.csv"
TURNS_DATA_FILE = DATA_DIR / "turns.csv"
EVENTS_DATA_FILE = DATA_DIR / "events.csv"
DATA_FILE = ROUND_DATA_FILE
