WORD_BANKS = {
    "abstract": [
        "Bond",
        "Year",
        "Source",
        "Point",
        "Game",
        "Blue",
        "Time",
        "Association",
        "Illness",
        "Intent",
        "Means",
        "Good",
        "Resolution",
        "Customs",
        "Relocation",
        "Memory",
        "Air",
        "Solution",
        "East",
        "Day",
        "Spirit",
        "Death",
        "Fire",
        "Angel",
        "Dance",
        "Luck",
        "Life",
        "Reason",
        "War",
        "Economy",
        "Freedom",
        "Space",
    ],
    "concrete": [
        "Chocolate",
        "Shell",
        "Elevator",
        "Penguin",
        "Ship",
        "Police",
        "Theater",
        "King",
        "Shoe",
        "Sea",
        "Chair",
        "Fork",
        "Tower",
        "Ice",
        "Ball",
        "Map",
        "Bottle",
        "Mouse",
        "Spider",
        "Cake",
        "Opera",
        "Stadium",
        "Fox",
        "Honey",
        "Lens",
        "Hospital",
        "Pen",
        "Snowman",
        "Moon",
        "Castle",
        "Car",
        "Clock",
    ],
}


BOARD_TEMPLATES = {
    "A": {
        "target": {"abstract": 3, "concrete": 2},
        "neutral": {"abstract": 4, "concrete": 5},
        "bomb": {"abstract": 1, "concrete": 1},
    },
    "B": {
        "target": {"abstract": 2, "concrete": 3},
        "neutral": {"abstract": 5, "concrete": 4},
        "bomb": {"abstract": 1, "concrete": 1},
    },
}
