FIXED_ROUND_BOARDS = {
    1: {
        "word_type": "concrete",
        "words": [
            "Chocolate",
            "Shell",
            "Elevator",
            "Penguin",
            "Ship",
            "Police",
            "Theater",
            "King",
            "Shoe",
            "Sea",
            "Chair",
            "Fork",
            "Tower",
            "Ice",
            "Ball",
        ],
    },
    2: {
        "word_type": "abstract",
        "words": [
            "Bond",
            "Year",
            "Source",
            "Point",
            "Game",
            "Blue",
            "Time",
            "Association",
            "Illness",
            "Intent",
            "Means",
            "Good",
            "Resolution",
            "Customs",
            "Relocation",
        ],
    },
    3: {
        "word_type": "abstract",
        "words": [
            "Air",
            "Solution",
            "East",
            "Day",
            "Spirit",
            "Death",
            "Fire",
            "Angel",
            "Dance",
            "Luck",
            "Life",
            "Reason",
            "War",
            "Economy",
            "Association",
        ],
    },
    4: {
        "word_type": "concrete",
        "words": [
            "Bottle",
            "Mouse",
            "Spider",
            "Cake",
            "Opera",
            "Stadium",
            "Fox",
            "Honey",
            "Lens",
            "Hospital",
            "Pen",
            "Snowman",
            "Moon",
            "Castle",
            "Car",
        ],
    },
}
