ABSTRACT_CATEGORIES = {
    "emotion": [
        "love",
        "fear",
        "joy",
        "sadness",
        "anger",
        "hope",
        "happiness",
        "surprise",
        "weakness",
        "shame",
        "loneliness",
        "peace",
    ],
    "social": [
        "friend",
        "family",
        "team",
        "community",
        "leader",
        "respect",
        "cooperation",
        "freedom",
        "support",
        "loyalty",
        "unity",
        "kindness",
    ],
    "cognitive": [
        "thought",
        "learning",
        "understanding",
        "idea",
        "reason",
        "focus",
        "imagination",
        "decision",
        "problem",
        "knowledge",
        "memory",
        "awareness",
    ],
}

CONCRETE_CATEGORIES = {
    "objects": [
        "apple",
        "book",
        "chair",
        "table",
        "lamp",
        "cup",
        "shoe",
        "door",
        "phone",
        "bag",
        "pen",
        "clock",
    ],
    "animals": [
        "dog",
        "cat",
        "fish",
        "horse",
        "elephant",
        "lion",
        "tiger",
        "monkey",
        "mouse",
        "rabbit",
        "sheep",
        "bear",
    ],
    "places": [
        "house",
        "school",
        "park",
        "river",
        "mountain",
        "street",
        "beach",
        "forest",
        "city",
        "market",
        "airport",
        "hospital",
    ],
}
